### ISSUE TITLE
CORS Variable

### ISSUE THREAD

**Issue by JonasGhost** [OktopUSP/oktopus#116]
Changing the base URL for the UI over a variable should be possible.  The base URL is hard coded so it is not possible to access it, if it is running on an remote machine.

https://github.com/OktopUSP/oktopus/blob/816262a3b857f2c6b05f7aa67d2e3b8aa4e8ab4c/backend/services/socketio/server.js#L10

https://github.com/OktopUSP/oktopus/blob/816262a3b857f2c6b05f7aa67d2e3b8aa4e8ab4c/backend/services/controller/internal/api/cors/cors.go#L11

**Comment by MuriloChianfa** [comment]
same here, the cors is allowing only localhost, if try to acess with 127.0.0.1 literal not working as expected
