### ISSUE TITLE
Address already in use

### ISSUE THREAD

**Issue by MuriloChianfa** [OktopUSP/oktopus#117]
hello man, im follow your instructions to setup project with docker but im receiving this error for oktopustr369 container startup:
![image](https://github.com/OktopUSP/oktopus/assets/60560085/11420109-08cd-41be-a1c4-78d0c78f870d)

but changing the default ip address for there container, it works fine, i imagine it's because are the same ip as defined for the gateway
https://github.com/OktopUSP/oktopus/blob/cb09b206b86aa117e709abe5d6de56ba7af06fae/devops/docker-compose.yaml#L18
https://github.com/OktopUSP/oktopus/blob/cb09b206b86aa117e709abe5d6de56ba7af06fae/devops/docker-compose.yaml#L85

i changed to 172.16.235.7 and get it up and running
anyone else had this problem too?

**Comment by leandrofars** [comment]
Yes, you're rigth. Already accepted your commit. Thanks for the contribution!
